---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qrpop.
--- DateTime: 3/10/23 3:49 PM
---
-- 比较两个标识是否一致
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0